### ISSUE TITLE
Minor bug on mobile frontend

### ISSUE THREAD

**Issue by JeswinSunsi** [Devansh3712/tsuki#3]
The sidebar doesn't have it's own background-color property, which causes [this issue](https://i.imgur.com/igFNfdN.jpg) on mobile devices. I recommend you set the sidebar to have a higher z-index and use background-color on it with the same color as the body background.

**Comment by RealSoerensen** [comment]
Using the built-in device toolbar in chrome I rendered the site as if I was on a mobile device. 
I tried to replicate the issue by changing the size but wasn't able to do so.
[Screenshot](https://imgur.com/a/iGCoLgo)
